name: global_advice_new
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.4.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  persistent_bottom_nav_bar:
    git:
      url: https://github.com/HamzaSamirAmmar/PersistentBottomNavBar.git
  easy_localization: ^3.0.7
  google_fonts: ^6.2.1
  get_it: ^7.7.0
  pinput: ^4.0.0
  dio: ^5.4.3+1
  dots_indicator: ^3.0.0
  readmore: ^3.0.0
  shared_preferences: ^2.2.3
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  equatable: ^2.0.5
  dartz: ^0.10.1
  dropdown_button2: ^2.3.9
  table_calendar: ^3.1.1
  givestarreviews: ^1.0.2
  carousel_slider: ^4.2.1
  loading_animation_widget: ^1.2.0+4
  flutter_easyloading: ^3.0.5
  awesome_dialog: ^3.2.1
  share: ^2.0.4
  provider: ^6.1.2
  lints: ^4.0.0
  uuid: ^4.4.2
  change_app_package_name: ^1.3.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/gaib-icon (2).png"
  min_sdk_android: 21

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Gilroy-Bold
      fonts:
        - asset: assets/font/Gilroy-Bold/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/font/Gilroy-Bold/Gilroy-Heavy.ttf
          weight: 900
        - asset: assets/font/Gilroy-Bold/Gilroy-Light.ttf
          weight: 100
        - asset: assets/font/Gilroy-Bold/Gilroy-Medium.ttf
          weight: 300
        - asset: assets/font/Gilroy-Bold/Gilroy-Regular.ttf
          weight: 200
    - family: Kufi-Bold
      fonts:
        - asset: assets/font/Kufi-Arabic/NotoKufiArabic-Bold.ttf
          weight: 900
